# Generated by Django 2.1.3 on 2018-11-25 23:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_framework.compat


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.PositiveSmallIntegerField(choices=[(1, 'Lower than'), (2, 'Greater than'), (3, 'Evolution')])),
                ('amount', models.FloatField(blank=True, null=True, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('evolution', models.FloatField(blank=True, null=True, validators=[rest_framework.compat.MinValueValidator(0)])),
                ('evolution_period', models.DurationField(blank=True, null=True, validators=[rest_framework.compat.MaxValueValidator(datetime.timedelta(days=1825))])),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('message_interval', models.DurationField(blank=True, null=True)),
                ('activated', models.BooleanField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=5)),
                ('symbol', models.CharField(max_length=5)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Coin'), (2, 'Currency')])),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='coin',
            field=models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='coin_alerts', to='pycoins.Symbol'),
        ),
        migrations.AddField(
            model_name='alert',
            name='currency',
            field=models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='currency_alerts', to='pycoins.Symbol'),
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
