# Generated by Django 2.1.3 on 2018-11-22 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycoins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField()),
                ('coin', models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='coin_rates', to='pycoins.Symbol')),
                ('currency', models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='currency_rates', to='pycoins.Symbol')),
            ],
        ),
    ]
